#cloud-config
users:
  - name: shibegora
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${vms_ssh_root_key}
package_update: true
package_upgrade: false
packages:
  - vim
  - wget
runcmd:
  - apt purge motd-news-config
  - rm -f /etc/update-motd.d/*